replicaCount: 3
image:
  repository: koroulis/test-argocd-app
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: test-argocd-app
  type: NodePort
  port: 443
ingress:
  enabled: true
  host: test-argocd-app.local
  path: /