apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "test-argocd-app.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "test-argocd-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "test-argocd-app.name" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["node", "/app/index.js"]
        workingDir: /app
        volumeMounts:
        - name: app-code
          mountPath: /app
        ports:
        - containerPort: 3000
      volumes:
      - name: app-code
        configMap:
          name: {{ include "test-argocd-app.name" . }}-code