apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-argocd-app.fullname" . }}
spec:
  selector:
    app: {{ include "test-argocd-app.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3000
  type: {{ .Values.service.type }}